### ISSUE TITLE
Ability to document AMQP input

### ISSUE THREAD

**Issue by pennstatephil** [spring-projects/spring-restdocs#539] opened 2018-08-06 19:03 UTC
I've been using rest docs and they work great for HTTP calls, but I have some microservices where the only input is a queue (i.e. read email messages off a queue). I'd like to somehow document the input of the message format to this queue (JSON body, required/optional fields, etc) but I don't believe there is currently a way to do it with rest docs... is there any way to expand this library (or is there a parallel project somewhere) that would programmatically allow me to generate this information?

**Comment by pennstatephil** [comment] 2018-08-06 19:46
If this is too close to #373, please feel free to close as duplicate (just found that)

**Comment by wilkinsona** [comment] 2018-08-07 07:40
Yep, I think this is a duplicate of #373.

**Closed by wilkinsona** 2018-08-07 07:40 UTC
