### ISSUE TITLE
Spring rest docs with Streaming Responses

### ISSUE THREAD

**Issue by cristianprofile** [spring-projects/spring-restdocs#669] opened 2020-02-20 08:03 UTC
To **test infinite streams** (for example, "text/event-stream" or "application/stream+json") using **webtestclient**, I need to exit the chained API (by using returnResult). Spring documentation recommends using the StepVerifier from the reactor-test module to do that, as the following example shows:

```
val eventFlux = result.getResponseBody()
StepVerifier.create(eventFlux) .expectNext(person) .expectNextCount(4)
.consumeNextWith { p -> ... } .thenCancel()
.verify()
```
Is there any feature in the roadmap to be able to create Spring rest docs documentation using this approach?

**Comment by wilkinsona** [comment] 2020-02-25 11:52
Duplicates #219. @cristianprofile please feel free to comment on that issue with any requirements you have, what you're particularly interested in, etc.

**Comment by izeye** [comment] 2020-03-04 23:49
This issue seems to be meant to be closed as a duplicate of #219 based on the Andy's comment.

**Comment by wilkinsona** [comment] 2020-03-05 06:24
Thanks, @izeye.

**Closed by wilkinsona** 2020-03-05 06:24 UTC
Labels: status: duplicate
