### ISSUE TITLE
relaxedResponseFields().and.andWithPrefix will ignore "ignoreUndocumentedFields"

### ISSUE THREAD

**Issue by someok** [spring-projects/spring-restdocs#420] opened 2017-08-27 16:45 UTC
I found `and` and `andWithPrefix` method will return a new `ResponseFieldsSnippet`, but ignore the field `ignoreUndocumentedFields`:

```
public final ResponseFieldsSnippet andWithPrefix(String pathPrefix,
			FieldDescriptor... additionalDescriptors) {
		List<FieldDescriptor> combinedDescriptors = new ArrayList<>();
		combinedDescriptors.addAll(getFieldDescriptors());
		combinedDescriptors.addAll(PayloadDocumentation.applyPathPrefix(pathPrefix,
				Arrays.asList(additionalDescriptors)));
		return new ResponseFieldsSnippet(combinedDescriptors, this.getAttributes());
	}
```

**Comment by wilkinsona** [comment] 2017-08-29 08:38
Duplicate of #400.

**Closed by wilkinsona** 2017-08-29 08:38 UTC
