### ISSUE TITLE
Externalize description texts

### ISSUE THREAD

**Issue by mduesterhoeft** [spring-projects/spring-restdocs#405] opened 2017-06-22 08:24 UTC
We are using `fieldWithPath(<path>).description(<description>)` as usual to document our request and response fields. Now technical writing comes into play and needs to work on the field descriptions. 

We would like to help our tech writers by giving them a central place to work on field descriptions. The easiest way I can think of is using resource bundles and just put the bundle key inside the field description. When spring-restdocs prepares the model map it could try to resolve descriptions against resource bundles.

As far as I could see in the source code there is no support for such a workflow.

What do you think? Is that something that you could imagine being part of spring-restdocs?

**Comment by mduesterhoeft** [comment] 2017-06-22 08:34
Having a second look at the open issues I found a related one
https://github.com/spring-projects/spring-restdocs/issues/248

**Comment by wilkinsona** [comment] 2017-06-22 11:32
IMO, #248 isn't just related. It's a duplicate of this issue.

**Closed by wilkinsona** 2017-06-22 11:32 UTC
