### ISSUE TITLE
Register default preprocessors during document configuration

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-restdocs#419] opened 2017-08-16 07:14 UTC
I couldn't find any issue linked to the feature that I needed so I am creating this.

The idea is to register default `OperationResponsePreprocessor` and `OperationRequestPreprocessor` that can be registered at the time of configuring the `MockMvcRestDocumentaton`.

It can look something like:

```java
MockMvcRestDocumentaton.documentConfiguration(...)
    .operationPreprocessors()
    .defaultReguestPreprocessors(...)
    .defaultResponsePreprocessors(...);
```

I don't know the internal of spring-restdocs to say whether this is easy or difficult to be done, or maybe it is not possible due the spring-mvc-test.

**Comment by wilkinsona** [comment] 2017-08-29 07:23
The current intention is that you use `alwaysDo` to achieve this:

```java
private MockMvc mockMvc;

private RestDocumentationResultHandler documentationHandler;

@Before
public void setup() {
	this.documentationHandler = document("{method-name}", 
			preprocessRequest(removeHeaders("Foo")),
			preprocessResponse(prettyPrint()));
	this.mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
			.apply(documentationConfiguration(this.restDocumentation))
			.alwaysDo(this.documentationHandler) 
			.build();
}
```

You then make your documentation calls like this:

```java
this.mockMvc.perform(get("/")) 
		.andExpect(status().isOk())
		.andDo(this.documentationHandler.document( 
				links(linkWithRel("self").description("Canonical self link"))
		));
```

Does that meet your needs?

**Comment by filiphr** [comment] 2017-08-29 18:44
Not really. If I want to invoke the documentation multiple times it will use the same name for it, right?

I know that it would be great to have a test that does only one thing. However, we have some more complex scenarios and we are testing an entire scenario in one test.

**Comment by wilkinsona** [comment] 2017-08-31 08:25
> If I want to invoke the documentation multiple times it will use the same name for it, right?

Yes, for  thespecific example that I showed. However, you can also use `{step}` if you are marking multiple `document` calls in the same test. Something like this:

```java
this.documentationHandler = document("{method-name}/{step}", 
	preprocessRequest(removeHeaders("Foo")),
	preprocessResponse(prettyPrint()));
```

You'd then end up with snippets in `foo/1`, `foo/2`, etc.

**Comment by wilkinsona** [comment] 2017-08-31 08:27
What you're asking for could still be used for cases where you don't want to use `alwaysDo`. If all you want to do is to set up some common pre- and post-processing, it would also streamline things a bit. There'd be no need for the `documentationHandler` field, for example.

**Comment by filiphr** [comment] 2017-08-31 08:53
Thanks for the info regarding the `{step}` it would work, but then I won't have nice descriptive names as the calls are to different services.

Actually in my case `alwaysDo` will not help me, due to the fact that not all requests return JSON (I know not good and we need to fix it 😄) and the handlers in this particular case are expecting JSON.

Is this something easy that could be done directly within `spring-restdocs` or it should be done within `spring-mvc-test`?

**Comment by wilkinsona** [comment] 2017-08-31 09:20
It should be possible to do it in REST Docs in a similar way to how default snippets are handled.

The first step would be a new configurer that allows the default request and response pre-processors to be configured. These would then be stored in the configuration map [as is currently done for the default snippets](https://github.com/spring-projects/spring-restdocs/blob/645a60a7879f8ea2783e219eace3cd8e570e9218/spring-restdocs-core/src/main/java/org/springframework/restdocs/config/SnippetConfigurer.java#L82-L83). They'd then be retrieved in `RestDocumentationGenerator` and combined with any that have been provided in the call to `document`. Again, this would be somewhat similar to what's [already being done for the default snippets](https://github.com/spring-projects/spring-restdocs/blob/645a60a7879f8ea2783e219eace3cd8e570e9218/spring-restdocs-core/src/main/java/org/springframework/restdocs/generate/RestDocumentationGenerator.java#L219-L229).

**Comment by filiphr** [comment] 2017-09-02 08:41
@wilkinsona I've created a PR for this functionality. I am open to suggestions and opinions in the PR 😄

**Comment by wilkinsona** [comment] 2017-11-22 09:21
Duplicate of #424

**Closed by wilkinsona** 2017-11-22 09:21 UTC
Labels: type: enhancement
