### ISSUE TITLE
rest-notes-spring-data-rest sample not passing tests out-of-the-box

### ISSUE THREAD

**Issue by dcalap** [spring-projects/spring-restdocs#471] opened 2018-01-10 12:03 UTC
Hi, 

If I clone the repo and mvn verify the sample rest-notes-spring-data-rest, tests crash because of a dependency problem. 

Any idea?

**Comment by wilkinsona** [comment] 2018-01-10 12:11
It works for me. Perhaps you can provide some information about exactly what you did and what the failure was?

**Comment by dcalap** [comment] 2018-01-10 12:15
Just did this:
cd /tmp
git clone https://github.com/spring-projects/spring-restdocs.git
cd spring-restdocs/samples/rest-notes-spring-data-rest/
./mvnw verify
and first error I get:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Unsatisfied dependency expressed through method 'dataSource' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:723) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
```

**Comment by wilkinsona** [comment] 2018-01-10 12:20
You may have a corrupted dependency in your local Maven cache. Try clearing that out (`./mvnw dependency:purge-local-repository`) and building again. If that doesn't work, the full error would also be useful.

**Comment by dcalap** [comment] 2018-01-10 12:32
Same error :(

Here is the complete trace: https://drive.google.com/file/d/1wEaJBkdLzHtBb-0HASFqv1vfiWoqYi2Z/view?usp=sharing

**Comment by wilkinsona** [comment] 2018-01-10 12:44
Thanks. Unfortunately, the full error hasn't proven useful. It confirms that Hibernate Validator failed to initialise but doesn't show why.

REST Docs doesn't do anything special with Hibernate Validator and neither I nor REST Docs' CI builds can reproduce the problem so there's not much that I can suggest. It would appear that there's a problem that's in some way specific to your environment that prevents Hibernate Validator from initialising.

This isn't a REST Docs-specific problem, and there's nothing that can be done in REST Docs to fix it so I'm going to close this issue. You could try running a test in the debugger to see if you can identify the problem with Hibernate Validator. Googling for the underlying error turns up a number of people who have encountered similar problems. Perhaps one of them will help.

**Closed by wilkinsona** 2018-01-10 12:44 UTC
Labels: status: waiting-for-feedback

**Comment by dcalap** [comment] 2018-01-10 12:52
Just removed the whole m2 and worked, thanks and sorry.
