### ISSUE TITLE
Is there a recommended way to document URI templates?

### ISSUE THREAD

**Issue by davidgoate** [spring-projects/spring-restdocs#497] opened 2018-03-28 17:47 UTC
Currently when I document endpoints I document using a sample HTTP request & response using the generated snippets which includes a sample URI, e.g:

`HTTP DELETE /resources/123/subresources/456/`

This is nice. However, it doesn't help the reader to determine what `123` and `456` necessarily relate to. Arguably it's obvious from the URI structure, however I'd like a way to document this:

`HTTP DELETE /resources/{resourceId}/subresources/{subresourceId}/`

prior to the HTTP request response sample. Obviously hardcoding  the HTTP request method or URI template  in the adoc file would be sub optimal, as it can easily become out of sync with the real controller endpoint URI.

Currently I resort to generating a snippet of my own in a test which uses reflection to grab the request mapping from the controller method. Obviously this does still reply on the template variable names being meaningful. But I wondered, does such a feature already exist somewhere that I've not come across yet?

**Comment by wilkinsona** [comment] 2018-03-28 18:52
This is a duplicate of #299. I've re-opened it so that it can be considered again. Please comment there, @davidgoate. My stance of documenting URIs has softened a little. While I don't think it's a good idea in a hypermedia-based API, there are valid reasons for wanting to do so when documenting an API that does not use hypermedia.

**Closed by wilkinsona** 2018-03-28 18:52 UTC
