### ISSUE TITLE
Field beneath an array that is sometimes null cannot have a type other than varies

### ISSUE THREAD

**Issue by nakulcg** [spring-projects/spring-restdocs#398] opened 2017-06-06 09:43 UTC
In a response containing an array, certain fields could be sometimes null and sometimes not. Currently JsonFieldTypeResolver marks them as Varies. This forces me to document the fields as Varies. Which IMO doesnt add any value to the docs. This leads to following error.

`org.springframework.restdocs.payload.FieldTypesDoNotMatchException: The documented type of the field '[].obj' is Array but the actual type is Varies`

Would it wise to make an exception for null?

here is an example patch

```diff
diff --git a/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonFieldTypeResolver.java b/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonFieldTypeResolver.java
index 25c373c..e618a4b 100644
--- a/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonFieldTypeResolver.java
+++ b/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonFieldTypeResolver.java
@@ -35,10 +35,10 @@ class JsonFieldTypeResolver {
                        JsonFieldType commonType = null;
                        for (Object item : (Collection<?>) field) {
                                JsonFieldType fieldType = determineFieldType(item);
-                               if (commonType == null) {
+                               if (commonType == null && fieldType !== JsonFieldType.NULL) {
                                        commonType = fieldType;
                                }
-                               else if (fieldType != commonType) {
+                               else if (fieldType != commonType && fieldType !== JsonFieldType.NULL) {
                                        return JsonFieldType.VARIES;
                                }
                        }
```

I could use `@JsonInclude(JsonInclude.Include.NON_NULL)` to prevent null fields in REST response but I'd like to avoid that and use null and have consistent REST response with all fields.

**Comment by wilkinsona** [comment] 2017-06-06 10:07
#365 appears to be related. Two questions:

 - What version of REST Docs are you using?
 - Have you marked the field as optional?

**Comment by nakulcg** [comment] 2017-06-06 10:12
1.
```
		<dependency>
			<groupId>org.springframework.restdocs</groupId>
			<artifactId>spring-restdocs-restassured</artifactId>
			<version>1.1.3.RELEASE</version>
			<scope>test</scope>
		</dependency>
```
2. Yes

**Comment by wilkinsona** [comment] 2017-06-06 10:44
Thanks. Just to be sure that we're looking at exactly the same thing, could you please put together a test that reproduces the behaviour you've described? One of the existing tests in `ResponseFieldsSnippetTests` would probably provide a good base to work from.

**Comment by wilkinsona** [comment] 2017-07-01 10:20
Thanks for reporting this, @nakulcg. The problem should now be fixed in the latest 1.2.x and 2.0 snapshots. By default, the type will still be resolved as `JsonFieldType.VARIES`, but you can now use `FieldDescriptor.type(JsonFieldType)` to override it as long as all of the fields are either `null` or are of the specified type.

**Comment by wilkinsona** [comment] 2017-07-01 10:21
Please note that the problem with the field not having to be marked as optional still exists. That will be tackled in #402 and I hope to include that fix in 1.2.2 as well.

**Comment by nakulcg** [comment] 2017-07-10 18:02
@wilkinsona thanks, I usually look up here https://mvnrepository.com/artifact/org.springframework.restdocs/spring-restdocs-core, is the latest build update there? Because the last update looks like may 12th

**Comment by wilkinsona** [comment] 2017-07-10 18:33
1.2.2 hasn't be released yet. You can using 1.2.2.BUILD-SNAPSHOT from https://repo.spring.io/snapshot in the meantime.

**Comment by wilkinsona** [comment] 2017-09-08 16:45
This doesn't work as intended when the array contains null and then non-null values.

**Closed** 2017-09-23 15:41 UTC
Labels: bug
