### ISSUE TITLE
Cannot document form parameters when contentType is multipart/form-data

### ISSUE THREAD

**Issue by fucct** [spring-projects/spring-restdocs#922] opened 2024-03-05 13:38 UTC
Hello,

In the case of requests in multipart form format, the form parameter is not documented.
An example of the request is as follows.

fix in #921 

```
Map<String, Object> params = new HashMap<>();
		params.put("password", "oldPassword");
		params.put("dvcid", "testDeviceId");

		// when
		MockMvcResponse response = given()
			.contentType(MediaType.MULTIPART_FORM_DATA_VALUE)
			.multiPart("profileImage", "test photo", "image/png")
			.formParams(params)
			.when()
			.post("/test/modify");

		response.prettyPrint();

		response.then()
			.apply(
				document("test-modify",
					ApiDocumentUtils.getDocumentRequest(),
					ApiDocumentUtils.getDocumentResponse(),
					formParameters(
						parameterWithName("oldPassword").attributes(emptyFormat()).description("password"),
						parameterWithName("dvcid").attributes(emptyFormat()).description("dvcid")
					),
					requestParts(
						partWithName("profileImage").attributes(emptyFormat(), required()).description("프로필 이미지 파일")
					)
				)
			)
			.statusCode(HttpStatus.OK.value());
```

**Comment by wilkinsona** [comment] 2024-03-05 16:10
Can you please share a complete yet minimal example that reproduces the problem? It's hard to assess the fix you're proposing in #921 without having a complete understanding of the problem. It looks like you're using REST Assured's MockMvc support but that's only an educated guess based on the names of the classes involved.

**Comment by fucct** [comment] 2024-03-06 15:17
here is sample code

https://github.com/fucct/restdocs-sample.git

**Comment by lefebvrecharlie** [comment] 2024-03-12 15:35
Hi. Same issue here with last version Spring Boot 3.2.3.

**Comment by JonasMatos0** [comment] 2024-04-10 10:51
@wilkinsona 
Could you please take a look on this item and let us know if there is an alternative at the moment?
Multipart requests apparently read only the multiPartFile, not the parameters along with the multipart form, therefore, we cannot document forms when there is a file being passed appropriately, for instance, a sign-up form with a pledge file, or documents

**Comment by wilkinsona** [comment] 2024-05-03 15:49
I think this is a bug in REST Assured.

Irrespective of whether or not its creating a multi-part request, any form parameters are applied to the underlying MockMvc request by calling `MockHttpServletRequestBuilder.param(String, String...)`. This method is intended for providing parameters that would have come from the query string or the body of an `application/x-www-form-urlencoded` request. Neither is applicable here as the parameter is intended for the body of an `multipart/form-data` request so it does not work correctly for multi-part requests.

By contrast, when using plain REST Assured where it makes an HTTP request, it correctly [converts the form params to parts in a multi-part request](https://github.com/rest-assured/rest-assured/blob/034ebfb0db4a6302e3bd429d26a2eb79e3190e9e/rest-assured/src/main/groovy/io/restassured/internal/RequestSpecificationImpl.groovy#L1400-L1402). It needs to do something similar in `MockMvcRequestSenderImpl` to map the form parameters to `MockPart` instances and then call `MockMultipartHttpServletRequestBuilder.part(Part...)`.

Unfortunately, you cannot work around this by calling `.multiPart("form1", "form1")` and `.multiPart("form2", "form2")`. This `multiPart` method is documented as being used to "specify a string to send to the server using multi-part form data" but it results in the MockMvc request having an additional `MockMultipartFile` rather than an additional `MockPart`. This should also be fixed in REST Assured and, unfortunately, I don't think there's anything that we can do to work around it in REST Docs.

**Closed by wilkinsona** 2024-05-03 15:49 UTC
Labels: status: waiting-for-triage, status: feedback-provided
